name: First Workflow
on:
  push:
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
     users: actions/checkout@v4
     - name: Print build started
     run: echo "build started"
